name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - trigger-ci-workflow
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "quickwit-*/**"


env:
  RUSTFLAGS: -Dwarnings
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  ci-passes:
    name: CI passes
    runs-on: ubuntu-latest
    # See https://github.com/quickwit-inc/quickwit-builder
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    needs:
      - lint
      - test
    steps:
      - run: exit 0

  lint:
    name: Lint (fmt, dependency check, clippy)
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests
      - uses: actions-rs/cargo@v1
        name: cargo deny
        with:
          command: deny
          args: check Licenses # check that all of deps have an ok license.
      - name: install cmake
        run: apt-get -y install cmake
      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --all-features --document-private-items
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: quickwit-ui
      - name: lint react app
        run: yarn --cwd quickwit-ui lint
        
  test:
    name: Run unit tests (no [ignored])
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest

    services:
      # PostgreSQL service container
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: quickwit-dev
          POSTGRES_PASSWORD: quickwit-dev
          POSTGRES_DB: quickwit-metastore-dev
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: quickwit-ui
      - name: Install JS dependencies
        run: yarn --cwd quickwit-ui install
      - name: Run react tests
        run: yarn --cwd quickwit-ui test
      - name: Compile tests
        run: cargo test --no-run --locked
      - name: Run tests
        run: cargo test --features=postgres -- --nocapture --quiet
        env:
          TEST_DATABASE_URL: postgres://quickwit-dev:quickwit-dev@postgres:5432/quickwit-metastore-dev

      # See #473 #472
      # - uses: actions-rs/cargo@v1
      #   name: cargo test failpoints
      #   with:
      #     command: test
      #     args: --features fail/failpoints test_failpoint -- --test-threads 1

  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
  #   services:
  #     localstack:
  #       image: localstack/localstack:latest
  #       ports:
  #         - "4566:4566"
  #       env:
  #         SERVICES: s3
  #         HOSTNAME_EXTERNAL: localstack
  #   env:
  #     AWS_ACCESS_KEY_ID   : "placeholder"
  #     AWS_SECRET_ACCESS_KEY: "placeholder"
  #     AWS_DEFAULT_REGION  : "localhost"
  #   container:
  #       image: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Create bucket in localstack
  #       run: /usr/local/bin/aws --endpoint-url=http://localstack:4566 s3 mb s3://quickwit-integration-tests
  #     - name: Run all tests.
  #       env:
  #         AWS_ACCESS_KEY_ID: dummy-access-key
  #         AWS_SECRET_ACCESS_KEY: dummy-secret-key
  #       run: cargo test --all-features
